# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Newreleases < Formula
  desc "A command line client for managing NewReleases projects."
  homepage "https://github.com/newreleasesio/cli-go"
  version "0.1.15"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.15/newreleases-darwin-amd64"
      sha256 "3d6041fdfaf96aef8e508d04f88572be36d34adb0e97d296263903fb2f98a423"

      def install
        bin.install "newreleases-darwin-amd64" => "newreleases"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.15/newreleases-darwin-arm64"
      sha256 "49668f7c402264393528c5d86d27299c965f680d2bc5360914842ecd672e0d26"

      def install
        bin.install "newreleases-darwin-arm64" => "newreleases"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.15/newreleases-linux-amd64"
      sha256 "64e33a34c985aca9c26836b7f826bbc669ef1e7d08b05e408ae7de2d91418831"

      def install
        bin.install "newreleases-linux-amd64" => "newreleases"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.15/newreleases-linux-armv6"
      sha256 "b751c1f92fd8f70a6809fcc05069f3f513c509bcd5248edf37627e4441346ce1"

      def install
        bin.install "newreleases-linux-armv6" => "newreleases"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.15/newreleases-linux-arm64"
      sha256 "d818f5974812eed1a8e8ec4b1915de8154b1a1ca3be7490cb0f426a407b5623d"

      def install
        bin.install "newreleases-linux-arm64" => "newreleases"
      end
    end
  end

  def caveats
    <<~EOS
      # Configuration

      This tool needs to authenticate to NewReleases API using a secret Auth Key
      that can be generated on the service settings web page
      https://newreleases.io/settings/api-keys.

      The key can be stored permanently by issuing interactive commands:

      newreleases configure

      or

      newreleases get-auth-key

      or it can be provided as the command line argument flag `--auth-key` on
      every newreleases command execution.

      # Usage

      Refer to the complete list of all commands on the project's README on
      https://github.com/newreleasesio/cli-go.
    EOS
  end

  test do
    system "#{bin}/newreleases version"
  end
end
