# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Newreleases < Formula
  desc "A command line client for managing NewReleases projects."
  homepage "https://github.com/newreleasesio/cli-go"
  version "0.1.16"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.16/newreleases-darwin-amd64"
      sha256 "8565b46a8ed373468841497caf4a80660145f514430fec3085a3b617c37c6368"

      def install
        bin.install "newreleases-darwin-amd64" => "newreleases"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.16/newreleases-darwin-arm64"
      sha256 "f747b2533a853a52dc5fae3da24c009b57f91929b1131a281445b90f2c25529d"

      def install
        bin.install "newreleases-darwin-arm64" => "newreleases"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.16/newreleases-linux-amd64"
      sha256 "f991736625c15993c0c0895414a92efc391c15ccd3b0f7a79f0198a85b8943bb"

      def install
        bin.install "newreleases-linux-amd64" => "newreleases"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.16/newreleases-linux-armv6"
      sha256 "1239877c16a6b11cd2a6d30ddeedb434b4dfd26d5c003bddaf9ff40c8fe42476"

      def install
        bin.install "newreleases-linux-armv6" => "newreleases"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.16/newreleases-linux-arm64"
      sha256 "6352214fc29b3a37192402181db1a4a8e6935c9ac4b13c1e4c31ab5f779cf92e"

      def install
        bin.install "newreleases-linux-arm64" => "newreleases"
      end
    end
  end

  def caveats
    <<~EOS
      # Configuration

      This tool needs to authenticate to NewReleases API using a secret Auth Key
      that can be generated on the service settings web page
      https://newreleases.io/settings/api-keys.

      The key can be stored permanently by issuing interactive commands:

      newreleases configure

      or

      newreleases get-auth-key

      or it can be provided as the command line argument flag `--auth-key` on
      every newreleases command execution.

      # Usage

      Refer to the complete list of all commands on the project's README on
      https://github.com/newreleasesio/cli-go.
    EOS
  end

  test do
    system "#{bin}/newreleases version"
  end
end
