# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Newreleases < Formula
  desc "A command line client for managing NewReleases projects."
  homepage "https://github.com/newreleasesio/cli-go"
  version "0.1.14"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.14/newreleases-darwin-arm64"
      sha256 "892275717151ffb6e6c98011752ffb5f4d23b8306ffed73e4cbe7a197d4145e1"

      def install
        bin.install "newreleases-darwin-arm64" => "newreleases"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.14/newreleases-darwin-amd64"
      sha256 "45eb7aa792c9bb8df22b4942d1f80764370d6193f9b91a1478ad941c3482da27"

      def install
        bin.install "newreleases-darwin-amd64" => "newreleases"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.14/newreleases-linux-amd64"
      sha256 "5300cdd562cd97c40e0ce1d1b2476cd0a4c26066514cfc31c845b6b9672023ec"

      def install
        bin.install "newreleases-linux-amd64" => "newreleases"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.14/newreleases-linux-arm64"
      sha256 "72bc653f1ec48b2f083532725d46bacbb63052a41da0400c4226558eb20600ae"

      def install
        bin.install "newreleases-linux-arm64" => "newreleases"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/newreleasesio/cli-go/releases/download/v0.1.14/newreleases-linux-armv6"
      sha256 "8b6a86838261fd2fd3b61e1f735e927bbf9591b30302d1bac7e74365480e647e"

      def install
        bin.install "newreleases-linux-armv6" => "newreleases"
      end
    end
  end

  def caveats
    <<~EOS
      # Configuration

      This tool needs to authenticate to NewReleases API using a secret Auth Key
      that can be generated on the service settings web page
      https://newreleases.io/settings/api-keys.

      The key can be stored permanently by issuing interactive commands:

      newreleases configure

      or

      newreleases get-auth-key

      or it can be provided as the command line argument flag `--auth-key` on
      every newreleases command execution.

      # Usage

      Refer to the complete list of all commands on the project's README on
      https://github.com/newreleasesio/cli-go.
    EOS
  end

  test do
    system "#{bin}/newreleases version"
  end
end
